name: Deploy Terraform Infrastructure to AWS

on:
  push:
    branches:
      - main  # Replace with your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Configure AWS credentials
      run: |
        echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
        echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
    
    - name: Change working directory to Terraform code
      with:
        path: Test

    - name: Initialize Terraform
      with:
        path: Test
        run: terraform init

    - name: Validate Terraform configuration
      run: terraform validate
      
    - name: Apply Terraform changes
      run: terraform apply -auto-approve
